[package]
name = "huldra-kernel"
description = "Huldra: a small Unix-like kernel written in Rust"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "huldra"
path = "src/main.rs"
test = false
bench = false

[dependencies]
huldra-abi = { path = "../libs/abi" }
huldra-buddy = { path = "../libs/buddy" }
huldra-cpio = { path = "../libs/cpio" }
huldra-elf = { path = "../libs/elf" }
huldra-ext2 = { path = "../libs/ext2" }
huldra-kalloc = { path = "../libs/kalloc" }
