[package]
name = "huldra-user"
description = "Huldra user space: runtime library (libc replacement) and programs"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"
test = false
bench = false

[dependencies]
huldra-abi = { path = "../libs/abi" }
huldra-kalloc = { path = "../libs/kalloc" }
huldra-archive = { path = "../libs/archive" }
huldra-hcc = { path = "../libs/hcc" }
huldra-net = { path = "../libs/net" }
