[package]
name = "huldra-user"
description = "Huldra user space: runtime library (libc replacement) and programs"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"
test = false
bench = false

[dependencies]
huldra-abi = { path = "../libs/abi" }
huldra-kalloc = { path = "../libs/kalloc" }
huldra-archive = { path = "../libs/archive" }
huldra-hcc = { path = "../libs/hcc" }
huldra-net = { path = "../libs/net" }
huldra-pkg = { path = "../libs/pkg" }
huldra-gfx = { path = "../libs/gfx" }
huldra-md = { path = "../libs/md" }
huldra-http = { path = "../libs/http" }
huldra-tls = { path = "../libs/tls" }
huldra-flate = { path = "../libs/flate" }
huldra-crypto = { path = "../libs/crypto" }
huldra-git = { path = "../libs/git" }
huldra-web = { path = "../libs/web" }
